In [1]:
from pyscf_custom_obj_updated import * 

In [2]:
%matplotlib notebook

H_bond=0.74
R= 2.0 # distance of H2 --- R --- H2

Ha1=(0, 0, -H_bond)
Ha2= (0, 0, 0)

Hb1= (0,0,R)
Hb2= (0,0,R+H_bond)

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(*Ha1, marker='o', color='green', label='systemA')
ax.scatter(*Ha2, marker='o', color='green', label='systemA')
ax.scatter(*Hb1, marker='o', color='red', label='systemB')
ax.scatter(*Hb2, marker='o', color='red', label='systemB')
plt.legend()
plt.show()


<IPython.core.display.Javascript object>

In [3]:
basis = '6-31g'
# basis = "sto3g"
# basis = 'augccpvtz'

In [4]:
mol_A = gto.Mole(atom='{} {} {} {}'.format('H',*Ha1) + "; " + '{} {} {} {}'.format('H',*Ha2),
               basis=basis,
               charge=0,
               spin=0)

print(mol_A.atom)
print('')
mol_A.build()

H 0 0 -0.74; H 0 0 0



In [5]:
mol_B = gto.Mole(atom='{} {} {} {}'.format('H',*Hb1) + "; " + '{} {} {} {}'.format('H',*Hb2),
               basis=basis,
               charge=0,
               spin=0)

print(mol_B.atom)
print('')
mol_B.build()

H 0 0 2.0; H 0 0 2.74



# Full start to finish!

In [6]:
env_method_subsystem_A = 'lda,vwn'
mol_A_subsystem = subsystem(mol_A, env_method_subsystem_A)

env_method_subsystem_B = 'lda,vwn'
mol_B_subsystem = subsystem(mol_B, env_method_subsystem_B)

In [7]:
list_of_subsystems = [mol_A_subsystem, mol_B_subsystem]
full_sys_method= 'lda,vwn'
freeze_thaw_conv = 1e-5
freeze_thaw_max_iter=100

Supersystem_obj = Supersystem( list_of_subsystems, full_sys_method, freeze_thaw_conv, freeze_thaw_max_iter)
Supersystem_obj.Run_full_embedded_WF_in_DFT_calc()

******************************************************************************** 

iter:  1:   subsystem:0   |δ_dmat|:6.562217e-01   |Tr[dmat.P]|:2.234004e-02
iter:  1:   subsystem:1   |δ_dmat|:1.312443e+00   |Tr[dmat.P]|:2.234004e-02
iter:  2:   subsystem:0   |δ_dmat|:1.561634e-01   |Tr[dmat.P]|:1.545878e-02
iter:  2:   subsystem:1   |δ_dmat|:3.123267e-01   |Tr[dmat.P]|:1.545878e-02
iter:  3:   subsystem:0   |δ_dmat|:1.051376e-01   |Tr[dmat.P]|:1.700792e-02
iter:  3:   subsystem:1   |δ_dmat|:2.102753e-01   |Tr[dmat.P]|:1.700792e-02
iter:  4:   subsystem:0   |δ_dmat|:8.023333e-02   |Tr[dmat.P]|:1.655454e-02
iter:  4:   subsystem:1   |δ_dmat|:1.604667e-01   |Tr[dmat.P]|:1.655454e-02
iter:  5:   subsystem:0   |δ_dmat|:6.287022e-02   |Tr[dmat.P]|:1.672344e-02
iter:  5:   subsystem:1   |δ_dmat|:1.257404e-01   |Tr[dmat.P]|:1.672344e-02
iter:  6:   subsystem:0   |δ_dmat|:4.959184e-02   |Tr[dmat.P]|:1.665952e-02
iter:  6:   subsystem:1   |δ_dmat|:9.918368e-02   |Tr[dmat.P]|:1.665952e-02
iter:

Overwritten attributes  get_hcore  of <class 'pyscf.scf.hf.RHF'>


converged SCF energy = -2.25179697174107
Supersystem FCI Energy: -2.30193151
******************************************************************************** 

******************************************************************************** 

DFT Supersystem calc: -2.26648026
converged SCF energy = -1.12418238571637
VQE-in-DFT Energy: -2.28576921
******************************************************************************** 

Error in Supersystem KS-DFT calc: -0.035451252606089945
Error in DFT-in-DFT calc: -0.06972893606997443
Error in WF-in-DFT calc: -0.01616220048873407
Error in VQE-in-DFT calc: -0.016162294080326767


In [8]:
# eri = mol_A_subsystem.mol.intor('int2e_sph', aosym='s1')
# eri.shape

In [9]:
# from pyscf.fci.direct_spin1 import absorb_h1e
# eri_new = absorb_h1e(scf.hf.get_hcore(mol_A_subsystem.mol),
#                      eri,
#                      mol_A_subsystem.mol.nao_nr(),
#                      mol_A_subsystem.mol.nelectron,
#                      fac=1)
# eri_new.shape

In [10]:
# eri_NEW = ao2mo.restore(1, 
#                         eri_new,
#                         mol_A_subsystem.mol.nao_nr())
# eri_NEW.shape

Trying with better functional for subsystem A

In [11]:
env_method_subsystem_A = 'b3lyp' # <-- better functional!
mol_A_subsystem = subsystem(mol_A, env_method_subsystem_A)

env_method_subsystem_B = 'lda,vwn'
mol_B_subsystem = subsystem(mol_B, env_method_subsystem_B)

In [12]:
list_of_subsystems = [mol_A_subsystem, mol_B_subsystem]
full_sys_method= 'lda,vwn'
freeze_thaw_conv = 1e-5
freeze_thaw_max_iter=50

Supersystem_obj = Supersystem( list_of_subsystems, full_sys_method, freeze_thaw_conv, freeze_thaw_max_iter)
Supersystem_obj.Run_full_embedded_WF_in_DFT_calc()

******************************************************************************** 

iter:  1:   subsystem:0   |δ_dmat|:6.562217e-01   |Tr[dmat.P]|:2.234004e-02
iter:  1:   subsystem:1   |δ_dmat|:1.312443e+00   |Tr[dmat.P]|:2.234004e-02
iter:  2:   subsystem:0   |δ_dmat|:1.561634e-01   |Tr[dmat.P]|:1.545878e-02
iter:  2:   subsystem:1   |δ_dmat|:3.123267e-01   |Tr[dmat.P]|:1.545878e-02
iter:  3:   subsystem:0   |δ_dmat|:1.051376e-01   |Tr[dmat.P]|:1.700792e-02
iter:  3:   subsystem:1   |δ_dmat|:2.102753e-01   |Tr[dmat.P]|:1.700792e-02
iter:  4:   subsystem:0   |δ_dmat|:8.023333e-02   |Tr[dmat.P]|:1.655454e-02
iter:  4:   subsystem:1   |δ_dmat|:1.604667e-01   |Tr[dmat.P]|:1.655454e-02
iter:  5:   subsystem:0   |δ_dmat|:6.287022e-02   |Tr[dmat.P]|:1.672344e-02
iter:  5:   subsystem:1   |δ_dmat|:1.257404e-01   |Tr[dmat.P]|:1.672344e-02
iter:  6:   subsystem:0   |δ_dmat|:4.959184e-02   |Tr[dmat.P]|:1.665952e-02
iter:  6:   subsystem:1   |δ_dmat|:9.918368e-02   |Tr[dmat.P]|:1.665952e-02
iter:

Supersystem FCI Energy: -2.30193151
******************************************************************************** 

******************************************************************************** 

DFT Supersystem calc: -2.26648026
converged SCF energy = -1.00195889749467
VQE-in-DFT Energy: -2.25218610
******************************************************************************** 

Error in Supersystem KS-DFT calc: -0.035451252606089945
Error in DFT-in-DFT calc: -0.06972893606997443
Error in WF-in-DFT calc: -0.04974541210510841
Error in VQE-in-DFT calc: -0.04974541123494536


In [13]:
basis = "sto3g"
# basis = '6-31g'
geometry = '{} {} {} {}'.format('H',*[0,0,0]) + "; " + '{} {} {} {}'.format('H',*[0,0,0.74])

mol_A_check_custom = gto.Mole(atom=geometry,
               basis=basis,
               charge=0,
               spin=0)
mol_A_check_custom.symmetry = False
print(mol_A_check_custom.atom)
print('')
mol_A_check_custom.build()

H 0 0 0; H 0 0 0.74



In [14]:
mol_A_check_custom_HF_obj = scf.RHF(mol_A_check_custom)
mol_A_check_custom_HF_obj.kernel()

H = Get_molecular_hamiltonian(mol_A_check_custom_HF_obj)

converged SCF energy = -1.11675930739643


In [15]:
from quchem.Hamiltonian_Generator_Functions import *
xyz = [('H', (0,0,0)), ('H', (0,0,0.74))]
Hamilt = Hamiltonian_PySCF('H2',
                          geometry =xyz,
                          basis=mol_A_check_custom.basis)

Hamilt.Get_Molecular_Hamiltonian()

quchem_H = Hamilt.MolecularHamiltonian

In [16]:
from openfermion.transforms import get_sparse_operator

In [17]:
sparse_H = get_sparse_operator(H)
sparse_quchem_H = get_sparse_operator(quchem_H)

In [18]:
# np.around(sparse_H.todense().real, 3)

In [19]:
# np.around(sparse_quchem_H.todense().real, 3)

In [20]:
from scipy.sparse.linalg import eigsh

eigvals_quchem_H, eigvecs_quchem_H= eigsh(sparse_quchem_H, which='SA')#, k=1)
ground_energy_quchem_H = min(eigvals_quchem_H)

eigvals_sparse_H, eigvecs_sparse_H= eigsh(sparse_H, which='SA')#, k=1)
ground_energy_sparse_H = min(eigvals_sparse_H)

print(ground_energy_quchem_H, ground_energy_sparse_H)

-1.1372838344884997 -1.1372838344885052


In [21]:
print(np.allclose(sparse_quchem_H.todense(), sparse_H.todense()))

np.abs(sparse_quchem_H.todense() - sparse_H.todense())

True


matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

In [22]:
a,b = Get_UCCSD_ijab_terms(4, 6)
a

[-1.0 [0^ 1^ 4 5] +
 1.0 [5^ 4^ 1 0],
 -1.0 [0^ 3^ 4 5] +
 1.0 [5^ 4^ 3 0],
 -1.0 [2^ 3^ 4 5] +
 1.0 [5^ 4^ 3 2]]

In [23]:
a2,b2 = Get_UCCSD_ijab_terms(4, 6)
a2

[-1.0 [0^ 1^ 4 5] +
 1.0 [5^ 4^ 1 0],
 -1.0 [0^ 3^ 4 5] +
 1.0 [5^ 4^ 3 0],
 -1.0 [2^ 3^ 4 5] +
 1.0 [5^ 4^ 3 2]]

In [24]:
N_electrons = Hamilt.molecule.n_electrons
N_orbitals = 2*Hamilt.molecule.n_orbitals
HF_state = Get_JW_HartreeF_state(N_electrons, N_orbitals)

ia_op_list , ia_theta_list = Get_UCCSD_ia_terms(N_electrons, N_orbitals)
ijab_op_list , ijab_theta_list = Get_UCCSD_ijab_terms(N_electrons, N_orbitals)
sparse_quchem_H = get_sparse_operator(quchem_H)

EXP = VQE_experiment(HF_state, 
                     sparse_quchem_H,
                     N_orbitals, 
                     ia_op_list,
                     ijab_op_list)


theta_guess = [*ia_theta_list, *ijab_theta_list]
theta_guess = [0,0,0]
opt_method = 'Nelder-Mead'
max_iter=100
opt = EXP.Run_VQE(theta_guess, max_iter, opt_method, doubles_first=True)

iter:  1:  var:[0.0, 0.0, 0.0]:   Energy:-1.116850e+00 
iter:  2:  var:[-0.0, -0.0, 0.0]:   Energy:-1.116910e+00 
iter:  3:  var:[-0.0, -0.0, 0.001]:   Energy:-1.117060e+00 
iter:  4:  var:[-0.0, -0.0, 0.001]:   Energy:-1.117060e+00 
iter:  5:  var:[-0.001, -0.001, 0.002]:   Energy:-1.117327e+00 
iter:  6:  var:[-0.001, -0.001, 0.002]:   Energy:-1.117623e+00 
iter:  7:  var:[-0.001, -0.001, 0.002]:   Energy:-1.117623e+00 
iter:  8:  var:[-0.003, -0.003, 0.005]:   Energy:-1.118419e+00 
iter:  9:  var:[-0.003, -0.004, 0.006]:   Energy:-1.118979e+00 
iter: 10:  var:[-0.004, -0.005, 0.009]:   Energy:-1.119756e+00 
iter: 11:  var:[-0.007, -0.009, 0.015]:   Energy:-1.121688e+00 
iter: 12:  var:[-0.009, -0.011, 0.021]:   Energy:-1.123330e+00 
iter: 13:  var:[-0.016, -0.017, 0.032]:   Energy:-1.126042e+00 
iter: 14:  var:[-0.024, -0.028, 0.05]:   Energy:-1.129450e+00 
iter: 15:  var:[-0.033, -0.039, 0.072]:   Energy:-1.131904e+00 
iter: 16:  var:[-0.039, -0.044, 0.082]:   Energy:-1.132137e+00 

In [25]:
opt.x

array([-7.42932197e-05,  7.41166164e-05,  1.12612428e-01])

In [26]:
list_theta_ia=[4,0]
list_theta_ijab=[2]

T=single_Trott_step_UCCSD(ia_op_list,
                          ijab_op_list,
                          list_theta_ia,
                          list_theta_ijab,
                          N_orbitals,
                          doubles_first=True)
Get_VQE_run_energy(T, HF_state, sparse_quchem_H)

-0.06082400556815577

In [29]:
# EXP._VQE_single_run([1,2,3], doubles_first=True)

energy_function = lambda theta_list: EXP._VQE_single_run(theta_list, doubles_first=True)

In [30]:
energy_function([1,4,3])

0.12010104751780287

In [31]:
options = {'maxiter': 500,
           'disp': True}

optimizer = minimize(energy_function,
                     [0,0,3],
                     args=(),
                     method='Nelder-Mead',
                     jac=None,
                     hess=None,
                     hessp=None,
                     bounds=None,
                     constraints=(),
                     tol=1e-5,
                     options=options)
optimizer.x

Optimization terminated successfully.
         Current function value: -1.137284
         Iterations: 45
         Function evaluations: 88


array([-2.63291880e-04, -2.11555897e-04,  3.25437491e+00])

In [32]:
energy_function([1,3,6])

-0.5938999853103051

In [33]:
EXP = VQE_Experiment_UPDATED(HF_state, 
                     sparse_quchem_H,
                     N_orbitals, 
                     ia_op_list,
                     ijab_op_list)

theta_guess = [*ia_theta_list, *ijab_theta_list]
theta_guess = [0,0,0]
opt_method = 'Nelder-Mead'
max_iter=100
opt = EXP.Run_VQE(theta_guess, max_iter, opt_method, doubles_first=True)



iter:  1:  var:[0.0, 0.0, 0.0]:   output:-1.116850e+00 
iter:  2:  var:[-0.0, -0.0, 0.0]:   output:-1.116910e+00 
iter:  3:  var:[-0.0, -0.0, 0.001]:   output:-1.117060e+00 
iter:  4:  var:[-0.0, -0.0, 0.001]:   output:-1.117060e+00 
iter:  5:  var:[-0.001, -0.001, 0.002]:   output:-1.117327e+00 
iter:  6:  var:[-0.001, -0.001, 0.002]:   output:-1.117623e+00 
iter:  7:  var:[-0.001, -0.001, 0.002]:   output:-1.117623e+00 
iter:  8:  var:[-0.003, -0.003, 0.005]:   output:-1.118419e+00 
iter:  9:  var:[-0.003, -0.004, 0.006]:   output:-1.118979e+00 
iter: 10:  var:[-0.004, -0.005, 0.009]:   output:-1.119756e+00 
iter: 11:  var:[-0.007, -0.009, 0.015]:   output:-1.121688e+00 
iter: 12:  var:[-0.009, -0.011, 0.021]:   output:-1.123330e+00 
iter: 13:  var:[-0.016, -0.017, 0.032]:   output:-1.126042e+00 
iter: 14:  var:[-0.024, -0.028, 0.05]:   output:-1.129450e+00 
iter: 15:  var:[-0.033, -0.039, 0.072]:   output:-1.131904e+00 
iter: 16:  var:[-0.039, -0.044, 0.082]:   output:-1.132137e+00 