# Open Shell Code tests


Broadly, there are three things we need to do make sure of before we can include the open shell code into the main repo.
1. Closed shell code is not affected in any way by the implementation of open shell.
2. Open shell code replicates closed shell results accurately.
3. Open shell results are accurate.

## 1.

We can check this using the existing tests for closed shell code.

## 2.

Overall
- Run closed shell experiemnts with both open and closed shell methods.
- Hamiltonians are numerically close

Localizers
- Active MOs should be consistent across un/restricted for closed shells.
- 

In [2]:
from nbed.driver import NbedDriver
from pathlib import Path

water_filepath = Path("molecules/water.xyz").absolute()

args = {
    "geometry": str(water_filepath),
    "n_active_atoms": 2,
    "basis": "STO-3G",
    "xc_functional": "b3lyp",
    "projector": "mu",
    "localization": "spade",
    "convergence": 1e-6,
    "savefile": None,
    "run_ccsd_emb": False,
    "run_fci_emb": False,
}

restric_driver = NbedDriver(
    geometry=args["geometry"],
    n_active_atoms=args["n_active_atoms"],
    basis=args["basis"],
    xc_functional=args["xc_functional"],
    projector=args["projector"],
    localization=args["localization"],
    convergence=args["convergence"],
    savefile=args["savefile"],
    run_ccsd_emb=args["run_ccsd_emb"],
    run_fci_emb=args["run_fci_emb"],
    force_unrestricted=False,
)

unrestric_driver = NbedDriver(
    geometry=args["geometry"],
    n_active_atoms=args["n_active_atoms"],
    basis=args["basis"],
    xc_functional=args["xc_functional"],
    projector=args["projector"],
    localization=args["localization"],
    convergence=args["convergence"],
    savefile=args["savefile"],
    run_ccsd_emb=args["run_ccsd_emb"],
    run_fci_emb=args["run_fci_emb"],
    force_unrestricted=True,
)



/home/mwilliams/.cache/pypoetry/virtualenvs/nbed-T5bcl2YH-py3.8/lib/python3.8/site-packages/pyscf/lib/misc.py:46: H5pyDeprecationWarning: Using default_file_mode other than 'r' is deprecated. Pass the mode to h5py.File() instead.
  h5py.get_config().default_file_mode = 'a'
/home/mwilliams/.cache/pypoetry/virtualenvs/nbed-T5bcl2YH-py3.8/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")


In [16]:
from numpy import all, allclose
for k in restric_driver.__dict__.keys():
    rk = getattr(restric_driver, k, 0)
    uk = getattr(unrestric_driver, k, 1)
    if not all(rk == uk):
        print(k)

localized_system
two_e_cross
dft_potential
molecule_info
v_emb
_restricted_scf
_global_ks
e_act
e_env
total_dm
g_act_and_env
g_act
_mu
_env_projector
embedded_scf
classical_energy


In [27]:
print(restric_driver.localized_system.active_MO_inds)
print(restric_driver.localized_system.beta_active_MO_inds)
print(unrestric_driver.localized_system.active_MO_inds)
print(unrestric_driver.localized_system.beta_active_MO_inds)

[0 1 2 3]
None
[0 1 2 3]
[0 1 2 3]



## 3.

This is the trickiest bit
- We can first check that the general behaviour is correct, what do we expect for the +1 and -1 ions of a molecule?
- Check results against physical limits, for instance if any are below the ground state these need to be explained.
- Find published energies of some example ions and compare to these.