In [1]:
import os
from nbed.driver import NbedDriver
import numpy as np

from nbed.ham_builder import HamiltonianBuilder
from openfermion import get_sparse_operator
import scipy as sp
    
from pyscf import gto, scf, fci, cc

/home/lex/anaconda3/envs/embed/lib/python3.9/site-packages/pyscf/lib/misc.py:46: H5pyDeprecationWarning: Using default_file_mode other than 'r' is deprecated. Pass the mode to h5py.File() instead.
  h5py.get_config().default_file_mode = 'a'


In [2]:
# get xyz file for water
notebook_dir = os.getcwd()
NBed_dir = os.path.dirname(notebook_dir)
Test_dir = os.path.join(NBed_dir, 'tests')
mol_dir = os.path.join(Test_dir, 'molecules')

water_xyz_path = os.path.join(mol_dir, 'water.xyz')

In [3]:
geometry_path = os.path.join(mol_dir, 'water.xyz')
# geometry_path = os.path.join(mol_dir, 'H4.xyz')

In [4]:
with open(geometry_path, 'r') as infile:
    xyz_string = infile.read()
    
print(xyz_string)

3

O   0.00000  0.0000000  0.1653507
H   0.00000  0.7493682 -0.4424329
H   0.00000 -0.7493682 -0.4424329 


In [5]:
# options
geometry = xyz_string
n_active_atoms=1
basis = 'STO-3G'
xc_functional = 'B3LYP'# 'lda, vwn' #'B3LYP'
run_virtual_localization = False

run_fci_emb = False
run_ccsd_emb = False
max_ram_memory = 8_000
_init_huzinaga_rhf_with_mu = False

max_hf_cycles=5000


projector = 'both'
localization = 'spade' # spade, ibo
occupied_threshold = 0.99
virtual_threshold = 0.95

In [6]:
driver = NbedDriver(geometry = geometry,
                    n_active_atoms=n_active_atoms,
                    basis = basis,
                    xc_functional = xc_functional,
                    run_virtual_localization = run_virtual_localization,
                    run_fci_emb = run_fci_emb,
                    run_ccsd_emb = run_ccsd_emb,
                    max_ram_memory = max_ram_memory,
                    _init_huzinaga_rhf_with_mu = _init_huzinaga_rhf_with_mu,
                    max_hf_cycles=max_hf_cycles,
                    occupied_threshold=occupied_threshold,
                    projector = projector,
                    localization = localization)

# FCI calc

In [8]:
charge=0
spin=0

full_system_mol = gto.Mole(atom= geometry[2:],
                      basis=basis,
                       charge=charge,
                       spin=spin,
                      )
full_system_mol.build()

global_rhf = scf.RHF(full_system_mol)
global_rhf.verbose=1
global_rhf.conv_tol = 1e-6
global_rhf.kernel()


## run FCI embedded
glob_FCI = fci.FCI(global_rhf)
glob_FCI.run()

print(f'full FCI energy: {glob_FCI.e_tot}')

full FCI energy: -75.01535247852487


# 1. Low-level whole system calculation

The first step is to run a DFT caluclation of the whole system.

In [9]:
### inputs

charge=0
spin=0

full_system_mol = gto.Mole(atom= geometry[2:],
                      basis=basis,
                       charge=charge,
                       spin=spin,
                      )
full_system_mol.build()

global_rks = scf.RKS(full_system_mol)
global_rks.verbose=1
global_rks.xc = xc_functional
global_rks.conv_tol = 1e-6
global_rks.kernel()

global_rks_Fock = global_rks.get_fock()
c_global_rks_full = global_rks.mo_coeff
global_rks_etot = global_rks.energy_tot()
global_rks.mo_energy = np.diag(c_global_rks_full.conj().T @ global_rks_Fock@ c_global_rks_full)
global_rks_mo_energies = global_rks.mo_energy 
global_rks_mo_energies

array([-18.83525318,  -0.93132671,  -0.43263415,  -0.23435814,
        -0.14179089,   0.35582625,   0.46190031])

In [9]:
# np.around(c_global_rks_full.conj().T @ global_rks_Fock@ c_global_rks_full, 5)

In [10]:
# checking global DFT calc
c_occ = global_rks.mo_coeff[:, global_rks.mo_occ>0]
dmat = 2* c_occ @ c_occ.T
e_tot = global_rks.energy_nuc() + global_rks.energy_elec(dm =dmat)[0]

np.isclose(global_rks.e_tot, e_tot)

True

In [11]:
# getting matrices manual
two_veff = global_rks.get_veff(dm=dmat)
vj = two_veff.vj
vk = two_veff.vk 

In [12]:
# calc xc contribution (DFT) via manual integral
ni = global_rks._numint
nelec, exc, vxc = ni.nr_rks(global_rks.mol, global_rks.grids, global_rks.xc, global_rks.make_rdm1())
exc - 0.25 * np.einsum('ij, ji ->', vk, dmat) 

-9.408825304427088

In [18]:
# check if this gives the same results
np.einsum('ij, ji ->',-0.25*vk, dmat) + exc

-9.408825304427088

In [19]:
two_veff.exc

-9.408825304427088

In [20]:
# two_veff construction
np.allclose(two_veff, vj - 0.5*vk + vxc)

True

In [17]:
print(two_veff.ecoul)
print(0.5 * np.einsum('ij, ji ->', vj, dmat) )

47.23189642113186
47.23189642113186


In [22]:
print(two_veff.exc + two_veff.ecoul)
print(0.5 * np.einsum('ij, ji ->', vj - 0.5*vk, dmat)+ exc)

37.82307111670474
37.823071116704746


In [20]:
## DFT fock matrix
F_obj = global_rks.get_fock()
F_manual = two_veff + global_rks.get_hcore()

np.allclose(F_obj, F_manual)

True

In [21]:
FF =  0.5*(vj - 0.5*vk) + global_rks.get_hcore()
np.einsum('ij, ji ->',FF, dmat) + exc

-84.4061685623297

In [22]:
np.allclose(two_veff, vj - 0.5*vk + vxc)

True

In [23]:
# subtract out the vxc part!!! (aka only leaving: 0.5*(vj - 0.5*vk) part!)

FF2 =  0.5*(two_veff - vxc)  + global_rks.get_hcore()
np.einsum('ij, ji ->',FF2, dmat) + exc

-84.4061685623297

In [24]:
global_rks.energy_elec()[0]

-84.40616856232967

# 2. Localize

We then use this object to find LOCALIZED systems (active and enviroment)

(more details given in notebook 2)

In [25]:
from nbed.localizers import (
    BOYSLocalizer,
    IBOLocalizer,
    Localizer,
    PMLocalizer,
    SPADELocalizer,
)

run_virtual_localization = False


localizers = {
    'boys':BOYSLocalizer,
    'ibo':IBOLocalizer,
    'pipek-mezey': PMLocalizer,
    'spade': SPADELocalizer
}

In [26]:
### inputs

charge=0
spin=0

full_system_mol2 = gto.Mole(atom= geometry[2:],
                      basis=basis,
                       charge=charge,
                       spin=spin,
                      )
full_system_mol2.build()

global_rks2 = scf.RKS(full_system_mol2)
global_rks2.verbose=1
global_rks2.xc = xc_functional
global_rks2.conv_tol = 1e-6
global_rks2.kernel()

global_rks_Fock = global_rks2.get_fock()
c_global_rks_full = global_rks2.mo_coeff
global_rks_etot = global_rks2.energy_tot()
global_rks2.mo_energy = np.diag(c_global_rks_full.conj().T @ global_rks_Fock@ c_global_rks_full)

In [27]:
localized_system = localizers[localization](global_rks2,
                                        n_active_atoms,
                                        occ_cutoff=occupied_threshold,
                                        virt_cutoff=virtual_threshold,
                                        run_virtual_localization=run_virtual_localization,
)

In [29]:
print(f'active inds: {localized_system.active_MO_inds}')
print(f'enviro inds: {localized_system.enviro_MO_inds}')

active inds: [0 1 2]
enviro inds: [3 4]


# 3. Run subsystem DFT (uses localized rks)

In [30]:
def rks_components(
    RKS_obj, subsystem_dm: np.ndarray):
    """Calculate the components of subsystem energy from a RKS DFT calculation.

    For a given density matrix this function returns the electronic energy, exchange correlation energy and
    J,K, V_xc matrices.

    Args:
        dm_matrix (np.ndarray): density matrix (to calculate all matrices from)

    Returns:
        Energy_elec (float): DFT energy defubed by input density matrix
        e_xc (float): exchange correlation energy defined by input density matrix
        J_mat (np.ndarray): J_matrix defined by input density matrix
    """
    dm_matrix = subsystem_dm
    # It seems that PySCF lumps J and K in the J array
    two_e_term = RKS_obj.get_veff(dm=dm_matrix)
    j_mat = two_e_term.vj
    # k_mat = np.zeros_like(j_mat)

    e_xc = two_e_term.exc
    # v_xc = two_e_term - j_mat

    energy_elec = (
        np.einsum("ij,ji->", RKS_obj.get_hcore(), dm_matrix)
        + two_e_term.ecoul
        + two_e_term.exc
    )

    return energy_elec, e_xc, j_mat

In [31]:
(e_act, e_xc_act, j_act) = rks_components(global_rks, localized_system.dm_active)

(e_env, e_xc_env, j_env) = rks_components(global_rks, localized_system.dm_enviro)

# Computing cross subsystem terms
two_e_term_total = global_rks.get_veff(
    dm=localized_system.dm_active + localized_system.dm_enviro
)
e_xc_total = two_e_term_total.exc

j_cross = 0.5 * (
    np.einsum("ij,ij", localized_system.dm_active, j_env)
    + np.einsum("ij,ij", localized_system.dm_enviro, j_act)
)
# Because of projection
k_cross = 0.0

xc_cross = e_xc_total - e_xc_act - e_xc_env

# overall two_electron cross energy
two_e_cross = j_cross + k_cross + xc_cross

energy_DFT_components = (e_act + e_env + two_e_cross + global_rks.energy_nuc())

if not np.isclose(energy_DFT_components, global_rks.e_tot):
    raise ValueError(
        "DFT energy of localized components not matching supersystem DFT")


In [34]:
# e_act, e_env, two_e_cross, localized_system, j_env = subsystem_dft(localized_system, localized_system.rks)

# DFT energy made from component parts
E_dft_from_components = e_act + e_env + two_e_cross + global_rks.energy_nuc()
np.isclose(global_rks.e_tot, E_dft_from_components)

True

In [35]:
dm_full = global_rks.make_rdm1()

full = global_rks.get_veff(dm=dm_full)
# print(full.exc + full.ecoul)
A= global_rks.get_veff(dm=localized_system.dm_active)
B= global_rks.get_veff(dm=localized_system.dm_enviro)
non_add = (full.exc + full.ecoul) - (A.exc + A.ecoul + B.exc + B.ecoul)

np.isclose(two_e_cross, non_add)

True

In [38]:
A_energy = np.einsum("ij,ji->", global_rks.get_hcore(), localized_system.dm_active) + (A.exc + A.ecoul)
B_energy = np.einsum("ij,ji->", global_rks.get_hcore(), localized_system.dm_enviro) + (B.exc + B.ecoul)
components = A_energy + B_energy + non_add + global_rks.energy_nuc()
np.isclose(global_rks.e_tot, components)

True

In [40]:
j_active = A.vj
E_manual = np.einsum("ij,ji->", global_rks.get_hcore() + j_active/2, localized_system.dm_active) + A.exc
np.isclose(A_energy, E_manual)

True

In [43]:
EE = (np.einsum("ij,ji->", global_rks.get_hcore(), localized_system.dm_active) +
      np.einsum("ij,ji->", global_rks.get_hcore(), localized_system.dm_enviro) +
      full.exc + full.ecoul
      + global_rks.energy_nuc()
    )
np.isclose(global_rks.e_tot, EE)

True

# 4. Get DFT potential

In [46]:
g_act_and_env = global_rks.get_veff(
    dm=(localized_system.dm_active + localized_system.dm_enviro)
)
g_act = global_rks.get_veff(dm=localized_system.dm_active)
dft_potential = g_act_and_env - g_act # + j_env

In [47]:
# localized_system.rks
dmat = 2* c_occ @ c_occ.T
print(np.allclose(dmat, localized_system.dm_active + localized_system.dm_enviro))

print(np.allclose(g_act_and_env, two_veff))

True
True


In [50]:
# vj_act = g_act.vj
# vk_act= g_act.vk

# ni = global_rks._numint
# nelec_act, exc_act, vxc_act = ni.nr_rks(global_rks.mol,
#                                         global_rks.grids, 
#                                         global_rks.xc,
#                                         localized_system.dm_active)


# np.allclose(g_act, (vj_act - 0.5*vk_act) + vxc_act)

dft_potential is

$$DFT\: potential = g[\gamma_{act} + \gamma_{env}] - g[\gamma_{act}]$$

In [52]:
rks_emb_mol = gto.Mole(atom= geometry[2:],
                      basis=basis,
                       charge=charge,
                       spin=spin,
                      )
rks_emb_mol.nelectron = 2 * len(localized_system.active_MO_inds) # <--change no e-
rks_emb_mol.build()

rks_emb = scf.RKS(rks_emb_mol)
rks_emb.verbose=1
rks_emb.xc = xc_functional
rks_emb.conv_tol = 1e-6

s_mat = global_rks.get_ovlp()
enviro_projector = s_mat@ localized_system.dm_enviro @ s_mat

h_core_Std = rks_emb.get_hcore()
rks_emb.get_hcore = lambda *args: h_core_Std + 1e6*enviro_projector + dft_potential

rks_emb.kernel()

-51.990665456924546

In [53]:
y_emb =  rks_emb.make_rdm1()
diff_gamma = y_emb - localized_system.dm_active

In [55]:
e_act

-77.37494139936761

In [56]:
(global_rks.energy_elec(dm=y_emb)[0]  
 + np.einsum("ij,ij->",  dft_potential+1e6*enviro_projector, diff_gamma) 
 )

-77.37494171972645

# WF approach

In [57]:
charge=0
spin=0

full_system_mol = gto.Mole(atom= geometry[2:],
                      basis=basis,
                       charge=charge,
                       spin=spin,
                      )
full_system_mol.nelectron = 2 * len(localized_system.active_MO_inds) # <- change number of e-
full_system_mol.build()

# HARTREE FOCK!
scf_method = scf.RHF(full_system_mol)
scf_method.verbose=1
scf_method.conv_tol = 1e-6

In [58]:
# scf_method = init_localised_RHF_obj(geometry, basis, charge, localized_system)
mu_level_shift = 1e6

# redefine core H
std_hcore = scf_method.get_hcore()
enviro_projector = s_mat@ localized_system.dm_enviro @ s_mat
scf_method.get_hcore = lambda *args: std_hcore + mu_level_shift*enviro_projector + dft_potential

scf_method.kernel()

-51.83101956837176

In [59]:
correction = np.einsum("ij,ji", mu_level_shift*enviro_projector + dft_potential,
                       localized_system.dm_active) # <--- different 
correction

16.255992534507456

In [60]:
scf_method.energy_elec()[0] - correction

-77.21529583116215

In [61]:
e_act

-77.37494139936761

In [62]:
## run FCI embedded
fci_scf_MU_embedded = fci.FCI(scf_method)

fci_scf_MU_embedded.run()

fci_scf_MU_embedded.e_tot

-51.83589627746254

In [63]:
e_corr = fci_scf_MU_embedded.e_tot - scf_method.e_tot
e_corr

-0.004876709090780196

In [64]:
E_emb_act = scf_method.energy_elec()[0] - correction + e_corr 
E_emb_full = E_emb_act + e_env + two_e_cross + global_rks.energy_nuc()
E_emb_full

-75.12311597493205

In [65]:
print(f'global DFT energy: {global_rks.e_tot}')
print(f'global FCI energy: {glob_FCI.e_tot}')
print()

print(f'emb error : {abs(E_emb_full - glob_FCI.e_tot)}')
print(f'DFT error : {abs(global_rks.e_tot - glob_FCI.e_tot)}')

global DFT energy: -75.27788483404674
global FCI energy: -75.01535247852487

emb error : 0.10776349640717342
DFT error : 0.26253235552186993


In [66]:
from nbed.scf import huzinaga_RHF, huzinaga_RKS

In [68]:
(c_active_embedded, 
 mo_energy, 
 dm_active_embedded,
 huzinaga_op_std,
 huz_rhf_conv_flag) =huzinaga_RHF(
    scf_method_HUZ,
    dft_potential,
    localized_system.dm_enviro,
    dm_conv_tol=1e-6,
    dm_initial_guess=None,
    use_DIIS= False,
)

hcore_std = scf_method_HUZ.get_hcore()
v_emb = huzinaga_op_std + dft_potential
scf_method_HUZ.get_hcore = lambda *args: hcore_std + v_emb
scf_method_HUZ.mo_coeff = c_active_embedded
scf_method_HUZ.mo_occ = scf_method_HUZ.get_occ(
    mo_energy, c_active_embedded
)
scf_method_HUZ.mo_energy = mo_energy
scf_method_HUZ.conv_check = huz_rhf_conv_flag

scf_method_HUZ.e_tot = scf_method_HUZ.energy_tot(dm=dm_active_embedded)


In [69]:
mo_energy

array([-20.22912626,  -0.71962271,  -0.36944532,   0.15734971,
         0.4309262 ,   0.6325906 ,   0.72378528])

In [71]:
overlap = np.einsum('ij, ki -> i', c_active_embedded.T,  huzinaga_op_std @ c_active_embedded)
overlap

array([ 5.91360847e-01,  4.11204883e-01, -1.11914838e-16,  1.44475353e-01,
        6.84298537e-01,  2.54867669e-01, -7.54246096e-02])

In [72]:
enviro_projector = s_mat@ localized_system.dm_enviro @ s_mat
overlap = np.einsum('ij, ki -> i', c_active_embedded.T,  enviro_projector @ c_active_embedded)

overlap_by_size = overlap.argsort()[::-1]

n_env_mo = len(localized_system.enviro_MO_inds)
frozen_enviro_orb_inds = overlap_by_size[:n_env_mo]
active_MOs_occ_and_virt_embedded = [
                mo_i
                for mo_i in range(c_active_embedded.shape[1])
                if mo_i not in frozen_enviro_orb_inds
            ]

c_selected = c_active_embedded[:, active_MOs_occ_and_virt_embedded]
mo_energy_act = np.diag(c_selected.conj().T @ scf_method_HUZ.get_fock()@ c_selected)
mo_energy_act

array([-20.22912626,  -0.71962272,  -0.36944533,   0.6325906 ,
         0.72378527])

In [73]:
np.around(c_selected.conj().T @ scf_method_HUZ.get_fock()@ c_selected, 3)

array([[-20.229,  -0.   ,   0.   ,   0.   ,   0.   ],
       [ -0.   ,  -0.72 ,   0.   ,   0.   ,  -0.   ],
       [  0.   ,   0.   ,  -0.369,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.633,  -0.   ],
       [  0.   ,  -0.   ,   0.   ,  -0.   ,   0.724]])

In [81]:
print(scf_method.mo_energy)

[-2.02291263e+01 -7.19622452e-01 -3.69445118e-01  6.32590515e-01
  7.23785410e-01  1.99999957e+06  1.99999984e+06]


In [82]:
## run FCI embedded
scf_method_HUZ.mo_coeff = c_active_embedded[:, active_MOs_occ_and_virt_embedded]

fci_scf_HUZ_embedded = fci.FCI(scf_method_HUZ)

fci_scf_HUZ_embedded.run()
fci_scf_HUZ_embedded.e_tot

-51.83589592603687

In [83]:
e_corr_HUZ = fci_scf_HUZ_embedded.e_tot - scf_method_HUZ.e_tot
e_corr_HUZ

-0.004876696459909624

In [84]:
correction_HUZ = np.einsum("ij,ji", v_emb,
                       localized_system.dm_active) # <--- different 
correction_HUZ

16.25599253451036

In [85]:
E_emb_act_HUZ = scf_method_HUZ.energy_elec(dm=dm_active_embedded)[0] - correction + e_corr_HUZ 
E_emb_full_HUZ = E_emb_act_HUZ + e_env + two_e_cross + global_rks.energy_nuc()


print(f'emb error : {abs(E_emb_full_HUZ - glob_FCI.e_tot)}')
print(f'DFT error : {abs(global_rks.e_tot - glob_FCI.e_tot)}')

emb error : 0.1077631449814902
DFT error : 0.26253235552186993


# Looking at localized system

In [86]:
print(np.around(localized_system.c_enviro, 3))

[[ 0.101  0.   ]
 [-0.353 -0.   ]
 [ 0.    -0.   ]
 [ 0.    -0.611]
 [ 0.557  0.   ]
 [-0.296 -0.446]
 [-0.296  0.446]]


In [87]:
enviro_projector = s_mat@ localized_system.dm_enviro @ s_mat

print(np.around(enviro_projector@ localized_system.c_loc_occ_and_virt, 3))

[[ 0.     0.     0.    -0.028  0.     0.     0.   ]
 [ 0.     0.     0.    -1.213 -0.     0.    -0.   ]
 [-0.    -0.    -0.     0.    -0.    -0.    -0.   ]
 [-0.    -0.    -0.     0.    -1.764 -0.     0.   ]
 [-0.    -0.    -0.     1.406  0.    -0.     0.   ]
 [ 0.     0.     0.    -1.339 -1.033  0.    -0.   ]
 [ 0.     0.     0.    -1.339  1.033  0.    -0.   ]]


In [88]:
proj_env = localized_system.dm_enviro/2 @ s_mat

print(np.around(localized_system.c_enviro, 3))
print()
print(np.around(proj_env @ localized_system.c_loc_occ_and_virt, 3))


[[ 0.101  0.   ]
 [-0.353 -0.   ]
 [ 0.    -0.   ]
 [ 0.    -0.611]
 [ 0.557  0.   ]
 [-0.296 -0.446]
 [-0.296  0.446]]

[[-0.    -0.    -0.     0.101  0.    -0.     0.   ]
 [ 0.     0.     0.    -0.353 -0.     0.    -0.   ]
 [-0.    -0.    -0.     0.    -0.    -0.    -0.   ]
 [-0.    -0.    -0.     0.    -0.611 -0.     0.   ]
 [-0.    -0.    -0.     0.557  0.    -0.     0.   ]
 [ 0.    -0.     0.    -0.296 -0.446  0.    -0.   ]
 [ 0.     0.     0.    -0.296  0.446  0.     0.   ]]


# Get projector onto enviroment

In [90]:
s_mat = global_rks.get_ovlp()
s_half = sp.linalg.fractional_matrix_power(s_mat, 0.5)
s_neg_half = sp.linalg.fractional_matrix_power(s_mat, -0.5)

# 1. Get orthogonal C matrix (localized)
c_loc_ortho = s_half @ localized_system.c_loc_occ_and_virt

# 2. Define projector that projects MO orbs of subsystem B onto themselves and system A onto zero state!
#    (do this in orthongoal basis!)
#    note we only take MO environment indices!
ortho_proj = np.einsum(
    "ik,jk->ij",
    c_loc_ortho[:, localized_system.enviro_MO_inds],
    c_loc_ortho[:, localized_system.enviro_MO_inds],
)

In [91]:
# note no two times for this dm!!!
dm = localized_system.c_enviro @ localized_system.c_enviro.T
ortho_proj2 =  s_half @ dm @ s_half
np.allclose(ortho_proj, ortho_proj2)

True

In [92]:
enviro_projector = s_neg_half @ ortho_proj @ s_half
print(np.around(enviro_projector@localized_system.c_enviro, 5))
print()

enviro_projector = dm @ s_mat
print(np.around(enviro_projector@localized_system.c_enviro, 5))
print()

print(np.around(localized_system.c_enviro, 5))

[[ 0.10066  0.     ]
 [-0.35251 -0.     ]
 [ 0.      -0.     ]
 [ 0.      -0.6113 ]
 [ 0.55729  0.     ]
 [-0.29575 -0.44592]
 [-0.29575  0.44592]]

[[ 0.10066  0.     ]
 [-0.35251 -0.     ]
 [ 0.      -0.     ]
 [ 0.      -0.6113 ]
 [ 0.55729  0.     ]
 [-0.29575 -0.44592]
 [-0.29575  0.44592]]

[[ 0.10066  0.     ]
 [-0.35251 -0.     ]
 [ 0.      -0.     ]
 [ 0.      -0.6113 ]
 [ 0.55729  0.     ]
 [-0.29575 -0.44592]
 [-0.29575  0.44592]]


In [93]:
enviro_projector = s_mat@ dm @ s_mat # paper definition!
print(np.around(enviro_projector@localized_system.c_active, 10))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [-0. -0. -0.]
 [-0. -0. -0.]
 [-0. -0. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [94]:
np.trace(s_mat@ localized_system.dm_enviro) # @ s_mat)

4.0

In [97]:
proj_act = localized_system.dm_active/2 @ s_mat # uses active dmat!

print(np.around(localized_system.c_active, 3))
print()
print(np.around(proj_act @ localized_system.c_loc_occ_and_virt, 3))

[[-0.226 -0.001 -0.996]
 [ 0.945  0.003 -0.021]
 [-0.004  1.    -0.   ]
 [ 0.    -0.    -0.   ]
 [ 0.53   0.002 -0.01 ]
 [-0.148 -0.001  0.015]
 [-0.148 -0.001  0.015]]

[[-0.226 -0.001 -0.996  0.    -0.    -0.    -0.   ]
 [ 0.945  0.003 -0.021 -0.     0.     0.     0.   ]
 [-0.004  1.     0.    -0.     0.    -0.     0.   ]
 [ 0.    -0.    -0.     0.    -0.     0.     0.   ]
 [ 0.53   0.002 -0.01  -0.     0.     0.     0.   ]
 [-0.148 -0.001  0.015  0.    -0.    -0.    -0.   ]
 [-0.148 -0.001  0.015  0.    -0.    -0.    -0.   ]]
