In [43]:
from nbed.ham_converter import HamiltonianConverter as HC

qham = HC({'IIIII': 0, "XIIIX":0.5, "IIXIY":0.25, "IIXIY":0.25, "IIIYY":0.2, "IZIIZ":0.2, "IXIII":0.2, "XIIII":0.5, 'XXXYY': 0.5})

from openfermion import count_qubits, taper_off_qubits, QubitOperator, get_sparse_operator
from qiskit.opflow import Z2Symmetries

sym = Z2Symmetries.find_Z2_symmetries(qham.qiskit)
print(sym.symmetries)
qis_tapered = sym.taper(qham.qiskit)

[Pauli('IIIYI'), Pauli('IIXII'), Pauli('XIIII')]
> /home/mwilliams/anaconda3/envs/nbed/lib/python3.7/site-packages/qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py(375)taper()
    373             import pdb; pdb.set_trace()
    374             tapered_ops_list = [
--> 375                 self._taper(operator, list(coeff))
    376                 for coeff in itertools.product([1, -1], repeat=len(self._sq_list))
    377             ]



In [44]:
import numpy as np
from functools import reduce
mat_list =[op.to_matrix() for op in qis_tapered.to_pauli_op()]
new_mat = reduce(lambda x, y: x+y, [op.to_matrix() for op in qis_tapered.to_pauli_op()]
)

In [52]:
ground_op=[op.to_pauli_op() for op in qis_tapered.to_pauli_op()][-1]
ground_op.oplist
ground_mat = [op.to_matrix() for op in qis_tapered.to_pauli_op()]

import numpy as np
np.min(eig(ground_mat)[0])

(-1.7998494048052494-9.23581587249644e-17j)

In [ ]:
of_ops = []
for op in qis_tapered.to_pauli_op():
    terms = []

In [54]:
[op.to_pauli_op() for op in qis_tapered.to_pauli_op()][0]

[QubitOperator('II', 0.5), QubitOperator()]

SummedOp([PauliOp(Pauli('II'), coeff=0.4999999999999999), PauliOp(Pauli('ZZ'), coeff=0.19999999999999993), PauliOp(Pauli('XI'), coeff=0.19999999999999993), PauliOp(Pauli('IX'), coeff=0.4999999999999999), PauliOp(Pauli('IY'), coeff=0.4499999999999998), PauliOp(Pauli('XY'), coeff=0.4999999999999999)], coeff=1.0, abelian=False)

In [46]:
qham._intermediate

{'IIIII': 0,
 'XIIIX': 0.5,
 'IIXIY': 0.25,
 'IIIYY': 0.2,
 'IZIIZ': 0.2,
 'IXIII': 0.2,
 'XIIII': 0.5,
 'XXXYY': 0.5}

In [47]:
from openfermion import get_sparse_operator
from scipy.sparse.linalg import eigsh
eigsh(get_sparse_operator(qham.openfermion))

(array([-1.7998494 ,  1.7998494 , -1.49285162, -1.44814557,  1.49285162,
         1.44814557]),
 array([[-0.00493706+0.15215357j,  0.06109154+0.18866039j,
          0.04929454-0.11982739j, -0.080834  -0.07411582j,
         -0.03882757-0.21024715j,  0.21035086-0.07890011j],
        [ 0.17202253+0.09865681j, -0.10590483+0.10935835j,
          0.19834032-0.07982834j,  0.01598872-0.22409166j,
         -0.10764366-0.07212071j,  0.03366345-0.10437463j],
        [-0.15215357-0.00493706j, -0.18866039+0.06109154j,
          0.11982739+0.04929454j, -0.07411582+0.080834j  ,
          0.21024715-0.03882757j, -0.07890011-0.21035086j],
        [-0.09865681+0.17202253j, -0.10935835-0.10590483j,
          0.07982834+0.19834032j, -0.22409166-0.01598872j,
          0.07212071-0.10764366j, -0.10437463-0.03366345j],
        [-0.00493706+0.15215357j,  0.06109154+0.18866039j,
         -0.04929454+0.11982739j,  0.080834  +0.07411582j,
          0.03882757+0.21024715j, -0.21035086+0.07890011j],
        [ 0.17

In [23]:
from numpy.linalg import eig
eig(mat_list[-1])
print(mat_list[0]

of_sparse = get_sparse_operator(of_tapered)


[[1.65+0.j 0.2 +0.j]
 [0.2 +0.j 1.25+0.j]]


(array([1.73284271+0.j, 1.16715729+0.j]),
 array([[ 0.92387953+0.j, -0.38268343+0.j],
        [ 0.38268343-0.j,  0.92387953+0.j]]))